POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8iLCJpZCI6IjZhNWY0NTM5Y2M2NzA1MWE1OGVhZGFjYiIsImlhdCI6MTc4NDY1ODgyMSwiZXhwIjoxNzg0NjYyNDIxfQ.ORj7eYiyaOIwLW_d5BT3jL5sZt_FhfO254UOAnHhwbo

{
    "title": "Thanking God",
    "author": "Chiidi Amaadi",
    "url": "example.com/blog/chichii"
}
